### PR TITLE
Change carousel to offseason images.

### PR DESCRIPTION
**Pull request by achen318**

### CODE REVIEW

**Comment by NebuDev14** [comment]
hi achen it looks good to me

**Comment by AngleSideAngle** [comment]
yep looks good

**Review by BenG49 — APPROVED** [review]
👍

**Comment by ThePotatoPowers** [comment]
Well I don't necessarily agree but it all looks good to me for now so I'll let it slide as PoSE

**Review by ThePotatoPowers — APPROVED** [review]

**Pull request merged**
